version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: pollpull
      POSTGRES_USER: pollpull
      POSTGRES_PASSWORD: pollpull

# services: 
#   poll: 
#   image: ubuntu/xenial
#   restart: always
#   ports: 
#     - "15000:8000"
#   environment: 
