# Generated by Django 2.2.4 on 2019-08-31 12:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=63, verbose_name='Текст')),
                ('grade', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127, verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=127, verbose_name='Текст')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_list', to='poll.Poll', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerGiven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answergiven_list', to='poll.Answer', verbose_name='Ответ на вопрос')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answergiven_list', to='poll.Poll', verbose_name='Опрос')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_list', to='poll.Question', verbose_name='Относится к вопросы'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_lead_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_leaded_to_list', to='poll.Question', verbose_name='Направление к вопросу'),
        ),
    ]
